title: Blog Of WolfHole
author: KEVIN SHEEP
email: kevinsheep@vip.qq.com
description: Hello World Of KevinSheep's GitHub Page.

plugins:
- jekyll-paginate
paginate: 3

minima:
  date_format: "%Y %b %d"
theme: minima
header_pages:
- readme.html


# permalink: /404.md