title: Blog Of WolfHole
author: KEVIN SHEEP
email: kevinsheep@vip.qq.com
description: Hello World Of KevinSheep's GitHub Page.


paginate: 2
paginate_path: "index:num"
paginate_file: index.html
baseurl: /blog

minima:
  date_format: "%Y %b %d"
theme: minima
header_pages:
- readme.html


# permalink: /404.md