title: 天花板 ceil.top
author: KEVIN SHEEP
email: kevinsheep@vip.qq.com
description: KevinSheep's GitHub Page.


paginate: 5
paginate_path: "index:num"
paginate_file: index.html
baseurl: /

minima:
  date_format: "%Y %b %d"
theme: dinky
header_pages:
- readme.html

permalink: pretty

# permalink: /404.md